//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingSystem.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sqlstatements {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sqlstatements() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankingSystem.Infrastructure.Resources.sqlstatements", typeof(sqlstatements).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT 
        ///    ClientId AS Id, 
        ///    Name, 
        ///    IdentificationNumber, 
        ///    IdentificationType, 
        ///    PersonType, 
        ///    LegalRepresentativeId
        ///FROM Client
        ///WHERE ClientId = @ClientId;.
        /// </summary>
        internal static string get_client_by_id {
            get {
                return ResourceManager.GetString("get_client_by_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Account 
        ///(Number, 
        ///Balance, 
        ///OriginDate, 
        ///CancellationDate, 
        ///MaturityDate, 
        ///DateLastModification) 
        ///OUTPUT 
        ///    INSERTED.AccountId AS Id, 
        ///    INSERTED.Number, 
        ///    INSERTED.Balance, 
        ///    INSERTED.OriginDate,
        ///    INSERTED.CancellationDate,
        ///    INSERTED.MaturityDate,
        ///    INSERTED.DateLastModification
        ///VALUES 
        ///(@Number, 
        ///@Balance, 
        ///GETDATE(), 
        ///@CancellationDate, 
        ///@MaturityDate,
        ///GETDATE());
        ///.
        /// </summary>
        internal static string insert_account {
            get {
                return ResourceManager.GetString("insert_account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Client
        ///(Name, 
        ///IdentificationNumber, 
        ///IdentificationType,
        ///PersonType, 
        ///LegalRepresentativeId)
        ///OUTPUT 
        ///    INSERTED.ClientId AS Id, 
        ///    INSERTED.Name, 
        ///    INSERTED.IdentificationNumber, 
        ///    INSERTED.IdentificationType, 
        ///    INSERTED.PersonType, 
        ///    INSERTED.LegalRepresentativeId
        ///VALUES 
        ///(@Name,
        ///@IdentificationNumber, 
        ///@IdentificationType, 
        ///@PersonType, 
        ///@LegalRepresentativeId);
        ///.
        /// </summary>
        internal static string insert_client {
            get {
                return ResourceManager.GetString("insert_client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO LegalRepresentative 
        ///(Name, 
        ///IdentificationNumber, 
        ///IdentificationType, 
        ///Phone) 
        ///OUTPUT 
        ///    INSERTED.LegalRepresentativeId AS Id, 
        ///    INSERTED.Name, 
        ///    INSERTED.IdentificationNumber, 
        ///    INSERTED.IdentificationType, 
        ///    INSERTED.Phone
        ///VALUES 
        ///(@Name, 
        ///@IdentificationNumber, 
        ///@IdentificationType,
        ///@Phone);
        ///.
        /// </summary>
        internal static string insert_legal_representative {
            get {
                return ResourceManager.GetString("insert_legal_representative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO Product 
        ///(Type, 
        ///Status, 
        ///MonthlyInterestPercentage, 
        ///TermMonths, 
        ///DateLastModification, 
        ///ClientId, 
        ///AccountId)
        ///OUTPUT 
        ///    INSERTED.ProductId AS Id, 
        ///    INSERTED.Type, 
        ///    INSERTED.Status, 
        ///    INSERTED.MonthlyInterestPercentage, 
        ///    INSERTED.TermMonths, 
        ///    INSERTED.DateLastModification, 
        ///    INSERTED.ClientId, 
        ///    INSERTED.AccountId
        ///VALUES 
        ///(@ProductType, 
        ///@ProductStatus, 
        ///@MonthlyInterestPercentage, 
        ///@TermMonths,
        ///GETDATE(), 
        ///@ClientId, 
        ///@AccountId);
        ///.
        /// </summary>
        internal static string insert_product {
            get {
                return ResourceManager.GetString("insert_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSERT INTO [Transaction] 
        ///(OriginDate, 
        ///Type, 
        ///Serial, 
        ///ProductId)
        ///VALUES 
        ///(@OriginDate, 
        ///@Type, 
        ///@Serial, 
        ///@ProductId);
        ///.
        /// </summary>
        internal static string insert_transaction {
            get {
                return ResourceManager.GetString("insert_transaction", resourceCulture);
            }
        }
    }
}
